### PR TITLE
MRK8 Reader and Writer

### PR DESCRIPTION
**Pull request by binaek**
**mrk8** Reader and Writer by implementing **MarcReader** and **MarcWriter** respectively.

Signed-off-by:Binaek Sarkar <binaek@alumnux.com>

### CODE REVIEW

**Comment by ksclarke** [comment]
Thanks! I should be able to merge this in this weekend.

Also, I use Checkstyle to check that code conforms to a few rules and it complained about the below issues:

```
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ freelib-marc4j ---
[INFO] Starting audit...
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:29:5: Missing a Javadoc comment. [JavadocMethod]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:29:29: Parameter input should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:41:22: Variable 'lines' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:49:20: Variable 'line' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:66:28: Parameter lines should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:71:16: Variable 'record' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:78:20: Variable 'tag' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:83:31: Variable 'field' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:88:28: Variable 'data' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:90:26: Variable 'indicator1' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:91:26: Variable 'indicator2' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:99:34: Variable 'subs' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:100: Trailing whitespace [RegexpSingleline]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:101:44: '{' is not preceded with whitespace. [WhitespaceAround]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:102:34: Variable 'subfield' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:113:40: Parameter indicator should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:117:32: Parameter substring should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:118:16: Variable 'leader' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:123:38: Parameter tag should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:6:8: Unused import - java.nio.ByteBuffer. [UnusedImports]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:28:5: Missing a Javadoc comment. [JavadocMethod]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:34:23: Parameter record should be final. [FinalParameters]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:35:23: Variable 'recordStringBuilder' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:37:16: Variable 'ldr' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:44:30: Variable 'controlField' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:53:27: Variable 'dataField' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamWriter.java:75:30: Parameter converter should be final. [FinalParameters]
```
They are small things (like making sure that things that can be declared as `final` are and that code has Javadocs). If you'd like to update the PR to handle these things that'd be great. Otherwise, I can add them this weekend before merging. Thanks again for the PR!

**Comment by binaek89** [comment]
@ksclarke Thanks for letting me know about the CheckStyle complaints. I have added the Javadocs and also made the parameters and arguments `final`, and updated the PR. Can you check whether this works for?

**Comment by ksclarke** [comment]
@thanks @binaek89 Just a few remaining ones:

```
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:90:22: Variable 'lines' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:98:20: Variable 'line' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:137:28: Variable 'data' should be declared final. [FinalLocalVariable]
[WARN] /home/travis/build/ksclarke/freelib-marc4j/src/main/java/org/marc4j/Mrk8StreamReader.java:151:34: Variable 'subfield' should be declared final. [FinalLocalVariable]
```
I can see this at: https://travis-ci.org/ksclarke/freelib-marc4j/builds/176610676

When you update the PR it does a new test build at: https://travis-ci.org/ksclarke/freelib-marc4j

If it fails, you can scroll down to the end of the black space on the right to see the reason for the failure (what Checkstyle is complaining about). Thanks!

**Comment by ksclarke** [comment]
It would be really great, too, if you created some tests for the reader/writer. That would speed along the merge process too. Thanks!

**Comment by ksclarke** [comment]
I squashed and merged. I rolled back the changes to the travis config too.

**Comment by binaek89** [comment]
Thanks @ksclarke ...

Sorry that I could not update the test cases. I do not have access to MRK8 files which I can publish to the repository. Would you happen to have any? Then I can put the files in and update the test cases.

**Comment by ksclarke** [comment]
I don't, but I think MARCEdit can generate them so maybe some of the same mrc records from this repo could be opened in MARCEdit and saved as mrk8 files? I'll want to add some test cases before pushing the updates to Maven Central.

**Pull request closed without merging**
