### PR TITLE
fix parse error in MarcStreamReader

### PR DESCRIPTION
**Pull request by cthdev**
Hi,

Here's my fix for parseRecord():
 - add an array of starting character positions and a hash of original index,
 - sort array of starting character positions
 - the loop iterates on the sorted array and use the hash to get index of tags and field lengths.

--
Thien

### CODE REVIEW

**Comment by ksclarke** [comment]
Looks good. Any chance I could get you to include a MARC record that demonstrates the problem with the code prior to the fix and a unit test along with this?  MARC record would go in src/test/resources. Test could go in MarcStreamReaderTest.java

Thanks!

**Comment by cthdev** [comment]
I've just added a unit test. Should I create a pull request for you?

**Comment by ksclarke** [comment]
It was picked up in this pull request.  So, I'll merge this tonight and push out a new version to the Maven repo tomorrow or Saturday.  Thanks again!

**Comment by cthdev** [comment]
Thanks :).

**Pull request merged**
